channels:
  - pytorch
  - nvidia
  - fair-robotics
  - conda-forge
  - defaults
dependencies:
    - python=3.9.0
    - pandas
    - numpy
    # MP_PyTorch dependencies
    - matplotlib
    # local packages
    - pip
    - pip:
        - -e MP_PyTorch